config/routes.rb
MackGourmetServer::Application.routes.draw do

  resources :restaurants
  resources :chefs
  resources :recipe_methods
  resources :recipes
  resources :ingredients
  resources :recipePhotos
  resources :recipe_photos
  resources :super_admins
  resources :students
  resources :developers

  apipie

  resources :concepts
  resources :admins
  devise_for :users
  resources :users

  root :to => "home#index"

  get "alterar_senha" => "users#edit"
  get "meu_perfil" => "users#edit"
  
  namespace :webservices do
    # Login
    post "login/signin"
    post "login/signinFacebook"
    post "login/signup"
    post "login/forgotPass"
    # Account
    post "account/updatePassword"
    get "account/getAbout"
    get "account/getNotifications"
    delete "account/deleteNotification"
    post "account/updatePhoto"
    put "account/updateAbout"
    # Concepts
    get "concepts/getConcepts"
    
    # get "places/getConcepts"
    # post "places/createFavorite"
    # delete "places/deleteFavorite"
    # get "places/getFavorites"
    # get "places/getClosestRecipes"
    # get "places/getRecipesByConcept"
    # get "places/findRecipe"
    # get "places/getIngredients"
    # get "places/getPayments"
    # get "places/getRatings"
    # post "places/createRating"
    # delete "places/deleteRating"
    # put "places/updateRating"
    # get "places/getRecipesMap"
 
    # get "orders/getChart"
    # get "orders/getMonths"
    # get "orders/getOrders"
    # get "orders/getMackGourmets"
    # get "orders/getChartConcepts"
    # get 'orders/getPendingMackGourmets'
    # get 'orders/getMackGourmetMonitor'

  end

  match ':controller(/:action(/:id))(.:format)'

end

app/views/admins/_form.html.erb
<style type="text/css">
.input-error {
  color :red;
}
</style>


<% fields1 = ["nome", "email"] %>
<% required_fields = ["nome", "email"] %>
<% displayFields1 = ["Nome", "E-mail"] %>

<% iterator = @admin %>
<% title = "Dados do Administrador" %>

    <div class="row">

<%= form_for(iterator, :validate => true)  do |f| %>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title"><%= title %></h3>
                </div>
                <div class="box-body">
                    <% fields1.each do |field| %>
                      <% i = fields1.index(field) %>
                      <div class="form-group">
                          <label for=""><%=displayFields1[i] %><span style="color:red"><%= required_fields.include?(field) ? "*" : "" %></span></label>
                          <%= f.text_field field, :placeholder => "#{displayFields1[i]}", :class => "form-control" %>
                      </div>
                    <% end %>


                    <div class="box-footer">
                       <%= f.submit "Salvar", :class => "btn btn-primary" %>
                    </div>
            </div>
      </div>  
     </div>  

<% end %>
</div>  

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<div class="row">

  <%= notice_helper %>
  <% cols = ["Nome","E-mail", "Opções"] %>
  <% path = "admins" %>
  <% remove_title = "Deseja remover o Admin?" %>
  <% new_button_title = "Novo Admin" %>
  <% iterator = @admins %>

  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
              <a href="<%= path %>/new" class="btn btn-primary pull-right" style="color:white; margin:10px;"> <%= new_button_title %></a>
          </div><!-- /.box-header -->

          <div class="box-body table-responsive">
              <table id="example1" class="table table-bordered table-striped table-hover">
                  <thead>
                      <tr>
                        <% cols.each do |col| %>
                            <th><%= col %></th>
                          <% end %>
                      </tr>
                  </thead>
                  <tbody>
                    <% iterator.each do |d| %>
                      <tr>
                          <td><%= d.nome %></td>
                          <td><%= d.email %></td>
                          <td> 
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Opções</button>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                  <span class="caret"></span>
                                  <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/<%= path %>/<%= d.id %>" data-confirm="<%= remove_title %>" data-method="delete" rel="nofollow"><i class="fa fa-trash-o"></i> Remover</a></li>
                                </ul>
                            </div>
                          </td>

                        </tr>
                      <% end %>
                  </tbody>
              </table>
                <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

          </div><!-- /.box-body -->
      </div><!-- /.box -->
  </div>
  <br>
</div>


  <script type="text/javascript">
      $(function() {
          $('#example1').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bAutoWidth": true
          });
      });
  </script>

app/views/admins/new.html.erb
<%= render 'form' %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>