config/routes.rb
MackGourmetServer::Application.routes.draw do

  resources :restaurants
  resources :chefs
  resources :recipe_methods
  resources :recipes
  resources :ingredients
  resources :recipePhotos
  resources :recipe_photos
  resources :super_admins
  resources :students
  resources :developers

  apipie

  resources :concepts
  resources :admins
  devise_for :users
  resources :users

  root :to => "home#index"

  get "alterar_senha" => "users#edit"
  get "meu_perfil" => "users#edit"
  
  namespace :webservices do
    # Login
    post "login/signin"
    post "login/signinFacebook"
    post "login/signup"
    post "login/forgotPass"
    # Account
    post "account/updatePassword"
    get "account/getAbout"
    get "account/getNotifications"
    delete "account/deleteNotification"
    post "account/updatePhoto"
    put "account/updateAbout"
    # Concepts
    get "concepts/getConcepts"
    
    # get "places/getConcepts"
    # post "places/createFavorite"
    # delete "places/deleteFavorite"
    # get "places/getFavorites"
    # get "places/getClosestRecipes"
    # get "places/getRecipesByConcept"
    # get "places/findRecipe"
    # get "places/getIngredients"
    # get "places/getPayments"
    # get "places/getRatings"
    # post "places/createRating"
    # delete "places/deleteRating"
    # put "places/updateRating"
    # get "places/getRecipesMap"
 
    # get "orders/getChart"
    # get "orders/getMonths"
    # get "orders/getOrders"
    # get "orders/getMackGourmets"
    # get "orders/getChartConcepts"
    # get 'orders/getPendingMackGourmets'
    # get 'orders/getMackGourmetMonitor'

  end

  match ':controller(/:action(/:id))(.:format)'

end

app/models/recipe.rb
class Recipe 
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  
  field :name, type: String
  field :description, type: String
  field :kind, type: String

  has_mongoid_attached_file :picture,
    :storage        => :s3,
    :bucket_name    => 'mackgourmet',
    :bucket         => 'mackgourmet',
    :path           => ':attachment/:id/:style.:extension',
    :s3_credentials => File.join(Rails.root, 'config', 's3.yml')

  belongs_to :concept
  belongs_to :user
  has_many :ingredients
  has_many :recipePhotos
  has_many :recipeMethods

  validates_presence_of :name, :message => "Digite um nome."
  validates_presence_of :description, :message => "Digite uma descrição para sua receita."

  def self.mapRecipes (array, current_user)
    array.map { |u| {
     :id => u.id,
     :name => u.name,
     :concept => {name: u.concept.name, id: u.concept.id},
     :picture => u.picture.url,
     :description => u.description,
     :address => [u.street, u.city, u.state, u.zip].compact.join(', '),
     :is_favorite => current_user.favorites.where(:recipe_id => u.id).count > 0
     }}
  end

  def self.mapRecipesMap (array)
    array.map { |u| {
     :id => u.id,
     :name => u.name,
     :current_recipe => getIngredient(u),
     :address => u.neighborhood,
     }}
  end

  def self.findRecipe (array, current_user)
    array.map { |u| {
     :id => u.id,
     :name => u.name,
     :concept => {name: u.concept.name, id: u.concept.id},
     :current_recipe => getIngredient(u),
     :picture => u.picture.url,
     :email => u.email,
     :zip => u.zip,
     :recipePhotos => RecipePhoto.mapRecipePhotos(u.recipePhotos),
     :description => u.description,
     :open_hours => Hour.mapHours(u.hours),
     :phone => u.phone,
     :has_rating => current_user.ratings.where(:recipe_id => u.id).count > 0,
     :url => u.url,
     :address => [u.street, u.city, u.state, u.zip].compact.join(', '),
     :is_favorite => current_user.favorites.where(:recipe_id => u.id).count > 0
     }}
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  # GET /recipes
  # GET /recipes.json
  def index
    respond_to do |format|
      format.html 
      format.json { render json: RecipesDatatable.new(view_context, current_user) }
    end    
  end

  # GET /recipe/1
  # GET /recipe/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: { profissionais: @recipe } }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /places/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    
    @recipe = Recipe.new(params[:recipe])
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save
        format.html { redirect_success("Receita criada com sucesso!",:recipes, :index)}
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        @recipe.save
        format.html { redirect_success("Loja alterada com sucesso!",:recipes, :index)}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy

    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
        format.html { redirect_success("Empresa removida com sucesso!",:recipes, :index)}
      format.json { head :no_content }
    end
  end
end

app/views/recipes/_form.html.erb
<style type="text/css">
.input-error {
  color :red;
}
</style>
<%= stylesheet_link_tag    "bootstrap3-wysihtml5.min" %>


<% fields1 = ["name","kind","description"] %>
<% required_fields = ["name"] %>
<% displayFields = ["Nome","Tipo", "Descrição" ] %>
<% iterator = @recipe %>
<% title = "Dados da Receita" %>


<%= form_for(iterator, :validate => true)  do |f| %>
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                
                <div class="box-header">
                    <h3 class="box-title"><%= title %></h3>
                </div>

                <div class="box-body">
                    <% fields1.each do |field| %>
                      <% i = fields1.index(field) %>
                      <div class="form-group">
                          <label for=""><%=displayFields[i] %><span style="color:red"><%= required_fields.include?(field) ? "*" : "" %></span></label>
                          <%= f.text_field field, :placeholder => "Digite o #{displayFields[i]}", :class => "form-control" %>
                      </div>
                    <% end %>

                    <% if current_user.isStudent? %>

                      <div class="form-group">
                          <label for="">Conceito<span style="color:red">*</span></label>
                            <%= f.select(:concept, options_for_select({current_user.concept.name => current_user.concept.id}))  %>
                      </div>

                    <% else %>
                          
                    <% json = [] %>
                    
                    <% emissores = Concept.all %>
                    <% emissores.each do |t| %>
                        <% json << [t.name,t.id] %>
                    <% end %>

                    <div class="form-group">
                        <label for="">Categoria<span style="color:red">*</span></label>
                        <% if iterator.concept.nil? %>
                            <%= f.select(:concept, options_for_select(json))  %>
                        <% else %>
                            <%= f.select(:concept, options_for_select(json,iterator.concept.id))  %>
                        <% end %>
                    </div>

                    <% end -%>


                    <div class="form-group">
                        <label for="">Foto</label>
                       <%= f.file_field :picture %>
                    </div>
                    <div class="box-footer">
                       <%= f.submit "Salvar", :class => "btn btn-primary" %>
                    </div>


                 </div>
              </div>
            </div>

     </div>  
<% end %>
<%= javascript_include_tag "bootstrap3-wysihtml5.all.min.js" %>

<script type="text/javascript">
  $(function () {
    //bootstrap WYSIHTML5 - text editor
    $(".textarea").wysihtml5();
  });
</script>

<%= javascript_include_tag "inputmask.js" %>
<%= javascript_include_tag "inputmask_extensions.js" %>

<script type="text/javascript">
jQuery(function($){
   $("#recipe_phone").inputmask({"mask": "(99)9999-9999"}); //specifying options only
   $("#recipe_cnpj").inputmask({"mask": "99.999.999/9999"}); //specifying options only
  });
</script>
<script type="text/javascript">
jQuery(function($){
   $("#recipe_zip").inputmask({"mask": "99999-999"}); //specifying options only
   $("#recipe_zip").change(function(){
      var cep_code = $(this).val();
      cep_code = cep_code.replace("-", "");
      if( cep_code.length <= 0 ) return;
      $.get("http://viacep.com.br/ws/" + cep_code + "/json",
         function(result){
            if( result.cep.length <= 0 ){
               alert(result.message || "Houve um erro desconhecido");
               return;
            }
            if( result.localidade.length <= 1 ){
               alert("CEP não encontrado, por favor preencha seu endereço");
               return;
            }
            $("#recipe_zip").val( result.cep );
            $("#recipe_city").val( result.localidade );
            $("#recipe_neighborhood").val( result.bairro );
            $("#recipe_street").val( result.logradouro );
            $("#recipe_state").val( result.uf );
         });
   });
       $(".numeric_input").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
             // Allow: Ctrl+A
            (e.keyCode == 65 && e.ctrlKey === true) || 
             // Allow: home, end, left, right, down, up
            (e.keyCode >= 35 && e.keyCode <= 40)) {
                 // let it happen, don't do anything
                 return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });

});
</script>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="row">
  <%= notice_helper %>
  <% cols = ["Nome", "Tipo", "Conceito","Usuário", "Opções"] %>
  <% path = "recipes" %>
  <% new_button_title = "Adicionar Receita" %>

  <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
              <a href="/<%= path %>/new" class="btn btn-primary pull-right" style="color:white; margin:10px;"> <%= new_button_title %></a>
          </div>

          <div class="box-body table-responsive">
              <table id="pads" class="table table-bordered table-striped table-hover" data-source="<%= recipes_url(format: "json") %>">
                  <thead>
                      <tr>
                        <% cols.each do |col| %>
                          <th><%= col %></th>
                        <% end %>
                      </tr>
                  </thead>
                  <tbody>
                  </tbody>
              </table>
              <br><br>
          </div><!-- /.box-body -->
      </div><!-- /.box -->
  </div><br>
</div>

  <script type="text/javascript">
      $(function() {
          $('#pads').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bAutoWidth": true,
              "bJQueryUI": true,
              "bProcessing": true,
              "bServerSide": true,
              "sAjaxSource": $('#pads').data('source')
          });
      });
  </script>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
  <%= notice_helper %>

<p id="notice"><%= notice %></p>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header">
                    	<h3 class="box-title">Dados do Loja</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <label for="">Id</label>
                        <%= @recipe.id %>
                    </div>
                    <div class="form-group">
                        <label for="">Data de Criação</label>
                        <%= @recipe.created_at.strftime("%d/%m/%Y %H:%M") %>
                    </div>

                    <div class="form-group">
                        <label for="">Nome</label>
                        <%= @recipe.name %>
                    </div>
 
                    <div class="form-group">
                        <label for="">Foto</label>
                        <%= link_to "Foto", @recipe.picture.url(:original) %>
                    </div>


                </div>
            </div>
        </div>
          <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Ingredientes</h3>
                </div>
                 <div class="box-body table-responsive">

	                    <table id="example3" class="table table-bordered table-striped">
	                <thead>
	                    <tr>
                        <th>Nome</th>
                        <th>Total</th>
                        <th>Unidade</th>
	                    </tr>
	                </thead>
	                <tbody>
	                  <% @recipe.ingredients.each do |d| %>
	                    <tr>
                          <td><%= d.name %></td>
                          <td><%= d.amount %>%</td>
                          <td><%= d.amount_unit %>%</td>
 	                      </tr>
	                    <% end %>
	                </tbody>
	            </table>
	        </div>

            </div>
        </div>

          <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Métodos</h3>
                </div>
                 <div class="box-body table-responsive">

	                    <table id="example2" class="table table-bordered table-striped">
	                <thead>
	                    <tr>
	                      <th>Nome</th>
	                      <th>Descrição</th>
	                    </tr>
	                </thead>
	                <tbody>
	                  <% @recipe.recipeMethods.each do |d| %>
	                    <tr>
	                        <td> <%= d.step %> </td>
	                        <td> <%= d.description %> </td>
	                      </tr>
	                    <% end %>
	                </tbody>
	            </table>
	        </div>

            </div>
        </div>
          <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Fotos</h3>
                </div>
                 <div class="box-body table-responsive">

                      <table id="example5" class="table table-bordered table-striped">
                  <thead>
                      <tr>
                        <th>Url</th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @recipe.recipePhotos.each do |d| %>
                      <tr>
                          <td> <%= link_to "Ver Foto", d.picture.url(:original) %> </td>
                        </tr>
                      <% end %>
                  </tbody>
              </table>
          </div>



    </div>

<%= javascript_include_tag "jquery.datatable.js" %>
<%= javascript_include_tag "dataTable.js" %>

<script type="text/javascript">
      $(function() {
          $('#example3').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bSearch": true,
              "bAutoWidth": true
          });
      });
      $(function() {
          $('#example2').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bSearch": true,
              "bAutoWidth": true
          });
      });
      $(function() {
          $('#example1').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bSearch": true,
              "bAutoWidth": true
          });
      });
      $(function() {
          $('#example4').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bSearch": true,
              "bAutoWidth": true
          });
      });
      $(function() {
          $('#example5').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bSearch": true,
              "bAutoWidth": true
          });
      });
      $(function() {
          $('#example6').dataTable({
              "bPaginate": true,
              "bLengthChange": true,
              "bFilter": true,
              "bSort": true,
              "bInfo": true,
              "bSearch": true,
              "bAutoWidth": true
          });
      });


</script>